# Generated by Django 3.1.7 on 2021-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(default='fashion', max_length=250, verbose_name='Category'),
        ),
    ]
